python scripts/pivot.py
python scripts/projection.py
python scripts/barchart.py
python scripts/barchartpercentage.py
python scripts/projectionchart.py
python scripts/personalprojectionchart.py
python scripts/twelvekcomparison.py
python scripts/wagepricecomparison.py
python scripts/growthcomparison.py
python scripts/d97enrollmentcomparison.py
python scripts/d97perstudent.py
python scripts/assessments.py
python scripts/assessmentcalcs.py